name: "Publish"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish articles on hashnode
        id: publish_hashnode
        uses: ./
        with:
          host: "wemakedevs.hashnode.dev"
          file: "post/blog/dynamic-routing-static-regeneration.md"
          hashnode_key: ${{secrets.HASHNODE_KEY}}
      - name: Get get output
        run: echo "me- ${{steps.publish_hashnode.outputs.result_json}} length ${{steps.publish_hashnode.outputs.result_summary}}"
