name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - run: npm run style:lint
      - run: npm run style:prettier
