name: Build test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 20.x
    - uses: actions/checkout@v3
    - run: yarn install --frozen-lockfile 
    - run: yarn build
    - run: yarn style:lint
    - run: yarn style:prettier
